# Generated by Django 5.0.6 on 2024-06-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_usn', models.CharField(max_length=30)),
                ('student_name', models.CharField(max_length=30)),
                ('student_sem', models.IntegerField()),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=40)),
                ('course_credits', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('enrollstudent', models.ManyToManyField(to='mysite.student')),
            ],
        ),
    ]
