# Generated by Django 5.0.6 on 2024-07-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_project_remove_student_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.CharField(choices=[('DG', 'Django'), ('FL', 'Flask'), ('PY', 'Python'), ('JS', 'JavaScript')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
